version: "3.9"
services:

  web:
    image: mmparla_web:1.0.0-development
    container_name: mmparla_web
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./web:/app
    depends_on:
      - api

  api:
    image: mmparla_api:1.0.0-development
    container_name: mmparla_api
    build: ./api
    ports:
      - 3000:3000
      - 3443:3443
    #entrypoint: ["node", "index.js", "--host", "0.0.0.0", "--disableHostCheck"]
    volumes:
      - ./api:/app
      - node_modules:/app/node_modules
      # - app-data:/app/temp
    environment:
      NODE_ENV: development
      # smtp_user: /run/secrets/smtp_user
      # smtp_password: /run/secrets/smtp_password
      # jwt_private_key: /run/secrets/jwt_private_key - Commented so we can use values from config instead of ENV for the development environment
      # db_user: /run/secrets/db_user
      # db_password: /run/secrets/db_password
      # mmparla_db:
    secrets:
      - smtp_user
      - smtp_password
      - smtp_email
      # - db_user
      # - db_password
      # - jwt_private_key
      # - mmparla_db
      - sendgrid_api_key
      - api_selfsigned.key
      - api_selfsigned.crt
    depends_on:
      - db

  db:
    image: mmparla_db:1.0.0-development
    container_name: mmparla_db
    build:
      context: .
      dockerfile: ./api/dockerfile.mongo
    ports:
      - 27017:27017
    volumes:
      - mmparla:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      # MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    # secrets:
    #  - db_user
    #  - db_password

volumes:
  mmparla:
  node_modules: # app-data:

secrets:
  smtp_user:
    file: ./secrets/smtp_user
  smtp_password:
    file: ./secrets/smtp_password
  smtp_email:
    file: ./secrets/smtp_email
  mmparla_db:
    file: ./secrets/mmparla_db
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  jwt_private_key:
    file: ./secrets/jwt_private_key
  sendgrid_api_key:
    file: ./secrets/sendgrid_api_key
  api_selfsigned.key:
    file: ./secrets/api_selfsigned.key
  api_selfsigned.crt:
    file: ./secrets/api_selfsigned.crt
