FROM node:16.15.0-alpine3.15

#Install packages
RUN apk update 
RUN apk add sudo
RUN apk add openssl
RUN apk add --no-cache bash
RUN sudo npm i -g sharp
RUN npm i nodemon -g --save-dev

#Add group(s)
RUN sudo addgroup app 
RUN sudo addgroup nodecert

#Adds user(s)
RUN adduser -S -G app app
RUN adduser app nodecert 
RUN adduser root nodecert

COPY ./init-create-nodecert-group.sh /etc

RUN mkdir /app && chown app:app /app
USER app
WORKDIR /app
COPY --chown=app:app package*.json ./
RUN npm i

COPY --chown=app:app . ./
ENV NODE_ENV=development
ENV jwt_private_key=
EXPOSE 3000 3443
CMD ["nodemon", "-L", "--watch", ".", "index.js", "--host", "0.0.0.0", "--disableHostCheck"]